### Purpose
# Fail2Ban Action for Notifiarr notifications
#### Install
# Download this file using the below curl command then move the file to your fail2ban action.d folder.
# curl -o notifiarr.conf https://notifiarr.com/scripts/fail2ban/notifiarr.conf
# On Most Ubuntu and Debian this can be accomplished with
# sudo curl -o /etc/fail2ban/action.d/notifiarr.conf https://notifiarr.com/scripts/fail2ban/notifiarr.conf
#### Setup
# Add the action to the default action or the jail(s) in your jail.local file
# action = notifiarr[bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s"]
#### Maintainers
# Bakerboy448, HalianElf

[Definition]
# Command executed when the jail starts
actionstart = curl -s -X POST "<url>" \
              -H "Content-Type: application/json" \
              -H "x-api-key: <apikey>" \
              -H "User-Agent: <agent>" \
              -d '{"event": "start", "server_name": "<hostname>", "jail_name": "<name>"}'

# Command executed when the jail stops
actionstop = curl -s -X POST "<url>" \
             -H "Content-Type: application/json" \
             -H "x-api-key: <apikey>" \
             -H "User-Agent: <agent>" \
             -d '{"event": "stop", "server_name": "<hostname>", "jail_name": "<name>"}'

# Command executed when banning an IP
actionban = curl -s -X POST "<url>" \
            -H "Content-Type: application/json" \
            -H "x-api-key: <apikey>" \
            -H "User-Agent: <agent>" \
            -d '{"event": "ban", "server_name": "<hostname>", "jail_name": "<name>", "ip": "<ip>", "ban_length": "<bantime>", "failures": "<failures>", "time_of_ban": "<time>", "port": "<port>", "protocol": "<protocol>", "additional_info": {"ipfailures": "<ipfailures>", "ipjailfailures": "<ipjailfailures>"}}'

# Command executed when unbanning an IP
actionunban = curl -s -X POST "<url>" \
            -H "Content-Type: application/json" \
            -H "x-api-key: <apikey>" \
            -H "User-Agent: <agent>" \
            -d '{"event": "unban", "server_name": "<hostname>", "jail_name": "<name>", "ip": "<ip>"}'

[Init]
hostname = pi-hole
apikey =
url = https://notifiarr.com/api/v1/notification/fail2ban
version = 1.0.0
agent = <fail2ban_agent>/Fail2BanNotifiarr_<version>