[sshd]
enabled = true
chain = INPUT
port = ssh
protocol = tcp
filter = sshd[mode=aggressive]
logpath = /var/log/auth.log
maxretry = 5
bantime  = -1
action   = iptables-multiport[name=SSH, chain=INPUT, port="%(port)s", protocol="%(protocol)s"]
           notifiarr[bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s"]